name: APK Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v1
      - name: Setting up Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Fetch Packages
        run: flutter pub get
      #     - run: flutter test
      
      - name: Build APK
        run: flutter build apk

#       - name: echo apk file name
#         run: echo "${{steps.build_apk.outputs}}"
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
        # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: ${{steps.extract_branch.outputs.branch}}-release
#           path: build/app/outputs/apk/release/app-release.apk
          path: build/app/outputs/apk/release
        
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#flutter-app-team'
        if: always()
        
