name: APK Generator

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Fetch Packages
        run: flutter pub get
      #     - run: flutter test
      
      - name: Build APK
        run: flutter build apk -t lib/main-prod.dart --flavor prod

#       - name: echo apk file name
#         run: echo "${{steps.build_apk.outputs}}"
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
        # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: ${{steps.extract_branch.outputs.branch}}-release
#           path: build/app/outputs/apk/release/app-release.apk
          path: build/app/outputs/apk/release
        
